"""Change Batches and WorkCenters

Revision ID: c627d8569c70
Revises: 180688a648f6
Create Date: 2025-09-10 20:21:17.541061

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c627d8569c70"
down_revision: Union[str, Sequence[str], None] = "180688a648f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_shift_batch"), "batches", type_="unique")
    op.create_unique_constraint(
        "uq_batch_number_date", "batches", ["batch_number", "batch_date"]
    )
    op.drop_constraint(op.f("work_centers_code_key"), "work_centers", type_="unique")
    op.drop_column("work_centers", "code")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "work_centers",
        sa.Column("code", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint(
        op.f("work_centers_code_key"),
        "work_centers",
        ["code"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint("uq_batch_number_date", "batches", type_="unique")
    op.create_unique_constraint(
        op.f("uq_shift_batch"),
        "batches",
        ["shift_task_id", "batch_number", "batch_date"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
